### ISSUE TITLE
Is it possible to append plaintext to a note using python API?

### ISSUE THREAD

**Issue by deepcoder** [RhetTbull/macnotesapp#42]
Thank you for your work on this project!

I could not find any reference to adding text to an existing note, is this possible?

Thx!

**Comment by RhetTbull** [comment]
Yes you can by setting the body of the note to the new value. However, there are some important caveats. Through the Python API, `Note.body` is an HTML representation of the body and `Note.plaintext` is a plaintext representation. When you set the body, you must set it as HTML to preserve any formatting or line breaks. However, you will lose formatting specific to Notes (e.g. todo lists are converted to HTML bulleted lists, etc.) You will also lose attachments and you have would to re-apply them. This is due to severe limitations of the Notes AppleScript API which is used under the hood by macnotesapp. 

For example:

```python
"""Demonstrate appending to a note"""

import macnotesapp

notesapp = macnotesapp.NotesApp()
note = notesapp.make_note("Test Note", body="<div>This is a test note</div>")
note.body = note.body + "<div>This is a second paragraph</div>"
```

Here's a note that was created in Notes:

<img width="728" alt="Screenshot 2023-11-26 at 1 37 09 PM" src="https://github.com/RhetTbull/macnotesapp/assets/41546558/5fcc58b7-8ac1-4ee9-ac1b-039fc76e89ac">

And after appending, notice formatting is lost and the attachment is gone:

<img width="325" alt="Screenshot 2023-11-26 at 1 39 43 PM" src="https://github.com/RhetTbull/macnotesapp/assets/41546558/58866011-d83b-4616-ac67-577e2eb15b55">

I wish Apple provided a more robust interface but this is the best I can do given the currently hamstrung API.
